services:
  # tests:
  #   build: .
  #   command: npm run test:watch
  #   tty: true
  #   volumes:
  #     - .:/usr/app/
  #     - /usr/app/node_modules
  #   ports:
  #     - 3000:3000
  #   depends_on:
  #     - mongodb
  #   environment:
  #     MONGO_URI: mongodb://mongodb:27017
  mongodb:
    container_name: mongodb
    image: mongo:6.0.17
    command: ['--replSet', 'rs0', '--bind_ip_all', '--port', '27017']
    healthcheck:
      test: echo "try { rs.status() } catch (err) { rs.initiate({_id:'rs0',members:[{_id:0,host:'localhost:27017'}]}) }" | mongosh --port 27017 --quiet
      interval: 5s
      timeout: 30s
      start_period: 0s
      start_interval: 1s
      retries: 30
    ports:
      - '27017:27017'
    restart: always
    volumes:
      - ./mongodb:/data/db
